### ISSUE TITLE
pypi still links to non existing bitbucket project

### ISSUE THREAD

**Issue by dwt** [brandon-rhodes/backports.ssl_match_hostname#1]
see homepage link here https://pypi.org/project/backports.ssl_match_hostname/

**Comment by brandon-rhodes** [comment]
Unfortunately, PyPI does not allow that field to be edited once a particular version of a package has been uploaded — they removed that feature from PyPI several years ago:

https://github.com/pypa/warehouse/issues/2170

If you can convince them to make it editable, though, I'd be happy to have you re-open this issue so we can get it fixed!

**Comment by dwt** [comment]
The easiest way to fix this is to make a point x.y.1 release that just fixes the urls without changing any code. Do you see any reasons why that would break anything?

**Comment by brandon-rhodes** [comment]
If the other maintainer is interested in making a new release, I'll happily defer to their decision, as I believe it was them who made the past few releases — but my own objection is the same one expressed in the comments on the PyPI issue: it makes the project look more recently updated than it really in fact is. I myself as a PyPI user pay very heavy attention to how recent the most version of a package is, and would (and I know this is personal opinion) much prefer a few broken links, which I expect when releases are read-only, to a date that makes it looks like the software was just updated when in fact it's still the same.
