### ISSUE TITLE
Little problem

### ISSUE THREAD

**Issue by Fidgety8** [brandon-rhodes/backports.ssl_match_hostname#2]
Hi,
This problem I had is mostly my fault, I don't know if there's anything you can do to help anyone who follows the path I took.
I think it's my fault for not reading your txt files on here.
I'm not a huge programmer but recently I started again as I needed to have some things I do automated.
Basicly, I created a script that saved me some time managing my orders on kraken, which is a crypto exchange.
There is a few pages on there website that references websockets module for python to establish connections.
My program was complete except for the connections to the exchange. Their website explained the connection procedure and referenced websockets module for python. The page I was directed to said, backports.ssl_match_hostname was a dependency to run it.
It never said anything about it being needed for the 2+ versions of python.
It drove me nuts trying to get pip to install this and it telling me it wasn't on my system.
After a day or so I read your txt files on github and realized it was to bring functionality to older versions on python.
I actually ruined my Linux install by trying to follow instructions I found on a forum suggesting reinstalling python for linux mint.
I had backups so I didn't loose everything.
The info I needed to figure this out was in the docs on github, but I just thought you might like to know, there are websites giving faulty links to this without explaining why this should be a dependency. 
Like I said, I'm not a proper programmer like people on here, but, I had a nightmare due to trying to install this.
I thought you maybe, might like to send a email to the websites I'm talking about so other people don't follow my path. They just need to sate its only a dependency if you are running older python versions.
Regards!

**Comment by brandon-rhodes** [comment]
I'm sorry to hear that the web site's instructions generated extra work for you! Have you tried contacting them yourself, by any chance? And can you tell the last time the page was updated, compared to the rest of their site?

**Comment by Fidgety8** [comment]
Sorry, I forgot to write the link that I got really messed up on.
https://pypi.org/project/websocket-client/
This website is being referenced on a major US crypto exchange that I use. 
It took me some time to figure out my problem, but it's bad for people that are new to programming and linux.
Peace!

**Comment by Fidgety8** [comment]
Hi Brandon!, I saw your response after posting 2nd message sorry!
I wasn't posting this because it generated extra work for me, I was just thinking of other people experiencing the same situation.
No criticism intended. I know it's my fault for not checking txts here. I haven't coded for a long time, like 10 years long.

**Comment by brandon-rhodes** [comment]
Happily, it looks like they have a GitHub project:

https://github.com/websocket-client/websocket-client

You can probably open an issue there asking for the phrase “backports.ssl_match_hostname for Python 2.x” to be replaced with maybe the phrase “backports.ssl_match_hostname if you are going to be using websocket-client under Python 2.x”, and the maintainers could make the update.

**Comment by Fidgety8** [comment]
Sorry, I probably posted this in the wrong place.
Sometimes it's hard to understand what someone goes through trying to figure out why linux is throwing out red txt errors at you for a few hours while you try to fix it. 
Probably seemed like a bigger deal for me than anyone else lol.

**Comment by brandon-rhodes** [comment]
No problem, they didn't provide a link from their front page to GitHub, so it wasn't easy to determine the correct place! I'll go ahead and close this issue since I don't have access to their docs. I hope they are able to incorporate your suggestion and that their documentation doesn't cause anyone else any trouble.
